/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package command-line-arguments */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "wrapper.go"


#include <stdint.h>

#include "bitcoinfuzz/ffi.h"

typedef struct {
    char* data;
    int length;
} ByteArray;

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern int BTCDVerifyScript(ByteArray scriptSig, ByteArray scriptPubKey);
extern bf_result BTCDParseP2PMessage(ByteArray messageData);
extern bf_result BTCDAddrv2(ByteArray addrv2Data);
extern bf_result BTCDDesBlock(ByteArray scriptData);
extern bf_result BTCDMerkleRootCompute(ByteArray data);
extern bf_result BTCDSighashCompute(ByteArray txData, ByteArray scriptData, ByteArray sigData, uint32_t inputIndex, uint32_t nCodesep, uint64_t amount, uint32_t sighashType, int isV0);
extern bf_result BTCDTransactionEval(ByteArray data);
extern bf_result BTCDParsePSBT(ByteArray data);
extern bf_result BTCDAddress(ByteArray data);
extern bf_result BTCDBech32SegwitRoundtrip(ByteArray hrpData, int witver, ByteArray progData);
extern bf_result BTCDBech32ConvertBits(ByteArray data, int fromBits, int toBits, int pad);
extern bf_result BTCDBip32MasterKeygen(ByteArray data);
extern bf_result BTCDSignSchnorr(ByteArray privKey, ByteArray hash, ByteArray aux);
extern bf_result BTCDDecodeEllswift(ByteArray buffer);
extern bf_result BTCDRoundtripEllswift(ByteArray buffer);
extern bf_result BTCDSchnorrVerify(ByteArray buffer, ByteArray hash, ByteArray sig);
extern bf_result BTCDBip32DeserializeExtendedKey(ByteArray data);

#ifdef __cplusplus
}
#endif
