[build]
rustflags = [
    "-Z", "sanitizer=address",
    "-C", "passes=sancov-module",
    "-C", "llvm-args=-sanitizer-coverage-inline-8bit-counters",
    "-C", "llvm-args=-sanitizer-coverage-trace-compares",
    "-C", "llvm-args=-sanitizer-coverage-pc-table",
    "-C", "llvm-args=-sanitizer-coverage-level=4",
    "-C", "llvm-args=-simplifycfg-branch-fold-threshold=0"
]